### ISSUE TITLE
Update to N0067

### ISSUE THREAD

**Issue by jessemapel** [conda-forge/cspice-feedstock#28]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

There is a new version of CSPICE that came out at the start of the year. It has a lot of new functionality including Mac/M1 support that would be great to have. https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/info/whatsnew.html#Version%2067%20---%20January%202022

I'm happy to help get this done.

**Comment by jessemapel** [comment]
This release also contains bug fixes for DSKX02 and SUBPNT that are currently being patched on this feedstock.

**Comment by AndrewAnnex** [comment]
Prs are welcome, I did some work to apply the patches and to add apple silicon/aarch64 compilations that may now be simplified with the new release, I’ve just been too busy recently. 

-Andrew Annex

**Comment by AndrewAnnex** [comment]
with #29 this issue is solved! closing this issue
